### ISSUE TITLE
Not Starts

### ISSUE THREAD

**Issue by pofdzm** [ConcreteMC/Alex#54]
pofdzm:[pofdzm]:~/Alex$ optirun ./Alex
 INFO|Program|Starting... 
 WARN|AudioEngine|Failed to init audio engine. FMod is required. System.DllNotFoundException: Unable to load shared library 'libfmod.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfmod.so: cannot open shared object file: No such file or directory                                                                                          
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at FmodAudio.Fmod.<>c.<.cctor>b__33_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at FmodAudio.Fmod.CreateSystem()
   at Alex.Audio.AudioEngine..ctor(IStorageSystem storageSystem, IOptionsProvider optionsProvider) in /home/runner/work/Alex/Alex/src/Alex/Audio/AudioEngine.cs:line 48                                                                                                                 
 INFO|PluginManager|Loaded 0 assemblies from 0 processed files.                                                                             
 INFO|PluginManager|Registered 0 plugin instances                                                                                           
Unhandled exception. System.TypeInitializationException: The type initializer for 'Alex.API.Graphics.PooledTexture2D' threw an exception.   
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'textureDisposalWarning' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Alex.API.Graphics.PooledTexture2D..cctor() in /home/runner/work/Alex/Alex/src/Alex.API/Graphics/GpuResourceManager.cs:line 515
   --- End of inner exception stack trace ---
   at Alex.API.Graphics.GpuResourceManager.CreateTexture2D(Object caller, GraphicsDevice graphicsDevice, Int32 width, Int32 height) in /home/runner/work/Alex/Alex/src/Alex.API/Graphics/GpuResourceManager.cs:line 150
   at Alex.API.Utils.TextureUtils.BitmapToTexture2D(Object owner, GraphicsDevice device, Image`1 image, Int64& byteSize) in /home/runner/work/Alex/Alex/src/Alex.API/Utils/TextureUtils.cs:line 74
   at Alex.Gui.GuiRenderer.LoadTextureFromEmbeddedResource(GuiTextures guiTexture, Byte[] resource) in /home/runner/work/Alex/Alex/src/Alex/Gui/GuiRenderer.cs:line 448
   at Alex.Gui.GuiRenderer.LoadEmbeddedTextures() in /home/runner/work/Alex/Alex/src/Alex/Gui/GuiRenderer.cs:line 253
   at Alex.Gui.GuiRenderer.Init(GraphicsDevice graphics, IServiceProvider serviceProvider) in /home/runner/work/Alex/Alex/src/Alex/Gui/GuiRenderer.cs:line 134
   at RocketUI.GuiManager.Init() in /_/src/RocketUI/GuiManager.cs:line 108
   at Alex.Alex.LoadContent()
   at Alex.Alex.Initialize() in /home/runner/work/Alex/Alex/src/Alex/Alex.cs:line 320
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Alex.Program.LaunchGame(LaunchSettings launchSettings) in /home/runner/work/Alex/Alex/src/Alex/Program.cs:line 72
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Alex.Program.Main(String[] args) in /home/runner/work/Alex/Alex/src/Alex/Program.cs:line 35

 The problem isn't related to the optirun probably cause the other build I downloaded earlier worked well with optirun (optirun is 
 the command to start the application on the nvidia gpu for optimus laptops). The reason I wanted the new build is the other one didn't connected to any server, so I just wanted to run the latest build before reporting it so I can be sure if it is already fixed or not.

**Comment by pofdzm** [comment]
I also installed fmod but issue is still there.

**Comment by kennyvv** [comment]
Thanks for the report! I know what the issue is and will fix it when i get home!

**Comment by pofdzm** [comment]
Thanks for the quick reply!

**Comment by kennyvv** [comment]
This should be fixed in the latest build. Please let me know so i can close this issue.

**Comment by pofdzm** [comment]
Yeah the game starts now.
