### ISSUE TITLE
Bedrock Cant Login

### ISSUE THREAD

**Issue by pofdzm** [ConcreteMC/Alex#55]
WARN|AudioEngine|Failed to init audio engine. FMod is required. System.DllNotFou
e to load shared library 'libfmod.so' or one of its dependencies. In order to hel
 problems, consider setting the LD_DEBUG environment variable: libfmod.so: cannot
t file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryNam
Error)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at FmodAudio.Fmod.<>c.<.cctor>b__33_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, B
onstructor)
   at System.Lazy`1.CreateValue()
   at FmodAudio.Fmod.CreateSystem()
   at Alex.Audio.AudioEngine..ctor(IStorageSystem storageSystem, IOptionsProvider
in /home/runner/work/Alex/Alex/src/Alex/Audio/AudioEngine.cs:line 48
 INFO|PluginManager|Loaded 0 assemblies from 0 processed files.
 INFO|PluginManager|Registered 0 plugin instances
 INFO|ResourceManager|Loading registries...
 INFO|ResourceManager|Loading resource pack (/root/.config/Alex/assets/java)...
 INFO|ResourceManager|Loading resource pack (/root/.config/Alex/assets/bedrock)...
 WARN|BedrockResourcePack|Duplicate geometry model: geometry.llamaspit
 INFO|ResourceManager|Imported 17104 blockstates from resourcepack in 9151ms!
 INFO|AtlasGenerator|Generating texture atlas out of 694 bitmaps...
 INFO|AtlasGenerator|TextureAtlas's generated in 474ms! (44.00MB)
 INFO|AtlasGenerator|Generating texture atlas out of 0 bitmaps...
 INFO|AtlasGenerator|TextureAtlas's generated in 31ms! (5.00KB)
 INFO|PluginManager|Enabled 0 plugins!
 INFO|Alex|Player skin loaded...
 INFO|Alex|Startup time: 00:00:18.3084537
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/pofdzm/.Xauthority which is owned by pofdzm.)
/usr/bin/xdg-open: line 881: x-www-browser: command not found
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/pofdzm/.Xauthority which is owned by pofdzm.)
/usr/bin/xdg-open: line 881: iceweasel: command not found
/usr/bin/xdg-open: line 881: seamonkey: command not found
/usr/bin/xdg-open: line 881: mozilla: command not found
/usr/bin/xdg-open: line 881: epiphany: command not found
/usr/bin/xdg-open: line 881: konqueror: command not found
/usr/bin/xdg-open: line 881: chromium: command not found
/usr/bin/xdg-open: line 881: chromium-browser: command not found
/usr/bin/xdg-open: line 881: google-chrome: command not found
/usr/bin/xdg-open: line 881: www-browser: command not found
/usr/bin/xdg-open: line 881: links2: command not found
/usr/bin/xdg-open: line 881: elinks: command not found
/usr/bin/xdg-open: line 881: links: command not found
/usr/bin/xdg-open: line 881: lynx: command not found
/usr/bin/xdg-open: line 881: w3m: command not found
xdg-open: no method available for opening 'https://www.microsoft.com/link'
 WARN|BedrockLoginState|Authentication issue. System.NullReferenceException: Object reference not set to an instance of an object.
   at Alex.Gamestates.Multiplayer.MultiplayerServerSelectionState.<>c__DisplayClass31_0.<OnJoinServerButtonPressed>g__Connect|0(PlayerProfile profile) in /home/runner/work/Alex/Alex/src/Alex/Gamestates/Multiplayer/MultiplayerServerSelectionState.cs:line 388
   at Alex.Gamestates.Login.BedrockLoginState.<>c__DisplayClass27_0.<OnLoginButtonPressed>b__0(Task`1 task) in /home/runner/work/Alex/Alex/src/Alex/Gamestates/Login/BedrockLoginState.cs:line 227

It didn't launched any browser (prob cause of i entered ./Alex with the sudo) so I go to the microsoft.com/link and linked my account with the code, microsoft page says it is succesfully linked but the client says "Authentication Failed".

**Comment by pofdzm** [comment]
Also it automatically logs me in without sudo.
